modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies."${mod_id}"]]
modId="neoforge"
type="REQUIRED"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="REQUIRED"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="ae2"
type="REQUIRED"
versionRange="[19.0.0,20.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="ae2ct"
type="OPTIONAL"
versionRange="[1.21.1,)"
ordering="AFTER"
side="CLIENT"

[[dependencies."${mod_id}"]]
modId="appmek"
type="OPTIONAL"
versionRange="[1.6.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="advanced_ae"
type="OPTIONAL"
versionRange="[1.6.12,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="merequester"
type="OPTIONAL"
versionRange="[1.21.1,)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="ae2craftingtime.mixins.json"
