modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies."${mod_id}"]]
modId="neoforge"
type="REQUIRED"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="REQUIRED"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="ae2"
type="REQUIRED"
versionRange="[19.0.24,20.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="ae2ct"
type="OPTIONAL"
versionRange="[1.0.1,)"
ordering="AFTER"
side="CLIENT"

[[dependencies."${mod_id}"]]
modId="appmek"
type="OPTIONAL"
versionRange="[1.6.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="advanced_ae"
type="OPTIONAL"
versionRange="[1.6.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="merequester"
type="OPTIONAL"
versionRange="[1.21.1,)"
ordering="AFTER"
side="CLIENT"

[[dependencies."${mod_id}"]]
modId="molecularmanipulator"
type="OPTIONAL"
versionRange="[1.3.9-hotfix,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="bmaddon"
type="OPTIONAL"
versionRange="[1.21.1-beta1,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="wcwt"
type="OPTIONAL"
versionRange="[1.3.8,)"
ordering="AFTER"
side="CLIENT"

[[dependencies."${mod_id}"]]
modId="ae2wtlib"
type="OPTIONAL"
versionRange="[19.5.1,)"
ordering="AFTER"
side="CLIENT"

[[dependencies."${mod_id}"]]
modId="extendedae_plus"
type="OPTIONAL"
versionRange="[1.6.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="megacells"
type="OPTIONAL"
versionRange="[4.11.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="ae2omnicells"
type="OPTIONAL"
versionRange="[1.1.6,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="projectcell"
type="OPTIONAL"
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="appliede"
type="OPTIONAL"
versionRange="[1.0.0-beta,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="appflux"
type="OPTIONAL"
versionRange="[1.21-2.1.4-neoforge,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="ae2craftingtime.mixins.json"

[[dependencies."${mod_id}"]]
modId="appbot"
type="OPTIONAL"
versionRange="[1.6.0-alpha.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="neoecoae"
type="OPTIONAL"
versionRange="[21.1.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="ae2lt"
type="OPTIONAL"
versionRange="[2.1.0-beta.2,)"
ordering="AFTER"
side="BOTH"
