package com.ctux.ae2craftingtime.testdriver;

public enum ScenarioState {
    STARTING,
    WORLD_READY,
    TERMINAL_OPEN,
    PLAN_OPEN,
    PLAN_STABLE,
    NEOECO_CPU_SELECTED,
    NEOECO_CRAFT_SUBMITTED,
    NEOECO_SAMPLE_RECORDED,
    NEOECO_PLAN_OPEN,
    BASE_CHECKED,
    SORTS_CHECKED,
    TOOLTIP_CHECKED,
    RESULT_WRITTEN,
    QUIT_REQUESTED,
    FAILED
}
