plugins {
    id 'java'
}

allprojects {
    group = 'com.ctux.ae2craftingtime'
    version = providers.gradleProperty('modVersion').get()

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'jacoco'

    jacoco {
        toolVersion = '0.8.14'
    }

    plugins.withType(JavaPlugin).configureEach {
        java {
            toolchain.languageVersion = JavaLanguageVersion.of(17)
        }

        tasks.withType(JavaCompile).configureEach {
            options.encoding = 'UTF-8'
        }

        tasks.withType(Test).configureEach {
            testLogging {
                events 'failed'
                exceptionFormat = 'full'
            }
        }

        tasks.withType(Jar).configureEach {
            from(rootProject.file('LICENSE')) {
                into 'META-INF'
                rename { 'LICENSE_ae2-crafting-time' }
            }
        }

        dependencies {
            testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
        }

        tasks.named('jacocoTestReport', JacocoReport).configure {
            dependsOn tasks.named('jacocoTestCoverageVerification')
            classDirectories.setFrom(files(classDirectories.files.collect {
                fileTree(dir: it, exclude: 'com/ctux/ae2craftingtime/mc1201/**')
            }))
            reports {
                xml.required = true
            }
        }

        tasks.named('jacocoTestCoverageVerification', JacocoCoverageVerification).configure {
            dependsOn tasks.named('test')
            classDirectories.setFrom(files(classDirectories.files.collect {
                fileTree(dir: it, exclude: 'com/ctux/ae2craftingtime/mc1201/**')
            }))
            if (project.name == 'shared') {
                violationRules.rule {
                    limit {
                        counter = 'LINE'
                        minimum = 1.0
                    }
                    limit {
                        counter = 'BRANCH'
                        minimum = 1.0
                    }
                }
            }
        }
    }
}
