package com.ctux.ae2craftingtime.mc1201.mixin;
import appeng.menu.me.crafting.CraftConfirmMenu; import appeng.menu.me.crafting.CraftingPlanSummary; import com.ctux.ae2craftingtime.core.PlanRecurrenceChunk; import com.ctux.ae2craftingtime.mc1201.RecurrentPlanEntry; import com.ctux.ae2craftingtime.mc1201.RecurrentPlanMenu; import com.ctux.ae2craftingtime.mc1201.StatsNetwork; import com.ctux.ae2craftingtime.mc1201.net.PlanRecurrenceS2C; import java.util.BitSet; import net.minecraft.server.level.ServerPlayer; import org.spongepowered.asm.mixin.Mixin; import org.spongepowered.asm.mixin.Shadow; import org.spongepowered.asm.mixin.Unique; import org.spongepowered.asm.mixin.injection.At; import org.spongepowered.asm.mixin.injection.Inject; import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
@Mixin(CraftConfirmMenu.class) public abstract class CraftConfirmMenuMixinSrg implements RecurrentPlanMenu {
 @Shadow private CraftingPlanSummary plan; @Unique private CraftingPlanSummary ae2craftingtime$sentPlan; @Unique private long ae2craftingtime$summaryRevision;
 @Inject(method="setPlan",at=@At("HEAD"),remap=false) private void clear(CraftingPlanSummary next,CallbackInfo ci){ae2craftingtime$summaryRevision++;for(var e:next.getEntries())((RecurrentPlanEntry)e).ae2craftingtime$recurrent(false);}
 @Inject(method="broadcastChanges",at=@At("TAIL")) private void send(CallbackInfo ci){var menu=(CraftConfirmMenu)(Object)this;if(!(menu.getPlayer() instanceof ServerPlayer player)||plan==null||plan==ae2craftingtime$sentPlan)return;ae2craftingtime$sentPlan=plan;var revision=++ae2craftingtime$summaryRevision;var entries=plan.getEntries();for(var offset=0;offset<entries.size();offset+=256){var count=Math.min(256,entries.size()-offset);var bits=new BitSet(count);for(var row=0;row<count;row++)if(((RecurrentPlanEntry)entries.get(offset+row)).ae2craftingtime$recurrent())bits.set(row);if(!bits.isEmpty())StatsNetwork.sendTo(player,PlanRecurrenceS2C.of(menu.containerId,revision,entries.size(),offset,count,bits));}}
 @Override public long ae2craftingtime$summaryRevision(){return ae2craftingtime$summaryRevision;}
 @Override public boolean ae2craftingtime$apply(PlanRecurrenceChunk chunk){if(plan==null||!chunk.validFor(((CraftConfirmMenu)(Object)this).containerId,ae2craftingtime$summaryRevision,plan.getEntries().size()))return false;var bits=chunk.rows();for(var row=bits.nextSetBit(0);row>=0;row=bits.nextSetBit(row+1)){var e=plan.getEntries().get(chunk.offset()+row);if(e.getMissingAmount()>0)((RecurrentPlanEntry)e).ae2craftingtime$recurrent(true);}return true;}
}
