package com.ctux.ae2craftingtime.mc1201.mixin;
import appeng.api.networking.IGrid; import appeng.api.networking.crafting.ICraftingPlan; import appeng.api.networking.security.IActionSource; import appeng.menu.me.crafting.CraftConfirmMenu; import appeng.menu.me.crafting.CraftingPlanSummary; import com.ctux.ae2craftingtime.core.PlanRecurrenceChunk; import com.ctux.ae2craftingtime.mc1201.PlanRecurrence; import com.ctux.ae2craftingtime.mc1201.RecurrentPlanEntry; import com.ctux.ae2craftingtime.mc1201.RecurrentPlanMenu; import com.ctux.ae2craftingtime.mc1201.StatsNetwork; import com.ctux.ae2craftingtime.mc1201.net.PlanRecurrenceS2C; import com.llamalad7.mixinextras.injector.wrapoperation.Operation; import com.llamalad7.mixinextras.injector.wrapoperation.WrapOperation; import java.util.BitSet; import net.minecraft.server.level.ServerPlayer; import org.spongepowered.asm.mixin.Mixin; import org.spongepowered.asm.mixin.Shadow; import org.spongepowered.asm.mixin.Unique; import org.spongepowered.asm.mixin.injection.At; import org.spongepowered.asm.mixin.injection.Inject; import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
@Mixin(CraftConfirmMenu.class) public abstract class CraftConfirmMenuMixinSrg implements RecurrentPlanMenu {
 @Shadow private CraftingPlanSummary plan; @Shadow(remap=false) private appeng.api.networking.IGrid getGrid() { throw new AssertionError(); } @Unique private CraftingPlanSummary ae2craftingtime$sentPlan; @Unique private final com.ctux.ae2craftingtime.core.PlanSummaryRevision ae2craftingtime$revisions = new com.ctux.ae2craftingtime.core.PlanSummaryRevision(); @Unique private final com.ctux.ae2craftingtime.core.PlanStoredVariantClientState ae2craftingtime$variantClient = new com.ctux.ae2craftingtime.core.PlanStoredVariantClientState(); @Unique private final com.ctux.ae2craftingtime.mc1201.StoredVariantMenuState ae2craftingtime$variants = new com.ctux.ae2craftingtime.mc1201.StoredVariantMenuState();
 @WrapOperation(method="broadcastChanges",at=@At(value="INVOKE",target="Lappeng/menu/me/crafting/CraftingPlanSummary;fromJob(Lappeng/api/networking/IGrid;Lappeng/api/networking/security/IActionSource;Lappeng/api/networking/crafting/ICraftingPlan;)Lappeng/menu/me/crafting/CraftingPlanSummary;",remap=false)) private CraftingPlanSummary mark(IGrid grid,IActionSource source,ICraftingPlan job,Operation<CraftingPlanSummary> original){var summary=original.call(grid,source,job);if(job instanceof PlanRecurrence r)for(var e:summary.getEntries())if(e.getMissingAmount()>0&&r.ae2craftingtime$recurrentKeys().contains(e.getWhat()))((RecurrentPlanEntry)e).ae2craftingtime$recurrent(true);return summary;}
 @Inject(method="setPlan",at=@At("HEAD"),remap=false) private void clear(CraftingPlanSummary next,CallbackInfo ci){ae2craftingtime$revisions.advance();ae2craftingtime$variantClient.reset(next==null?0:next.getEntries().size());com.ctux.ae2craftingtime.core.RecurrentMissing.clearPlan(next,CraftingPlanSummary::getEntries,e->{((RecurrentPlanEntry)e).ae2craftingtime$recurrent(false);((RecurrentPlanEntry)e).ae2craftingtime$storedVariant(false);});}
 @Inject(method="broadcastChanges",at=@At("RETURN")) private void send(CallbackInfo ci){var menu=(CraftConfirmMenu)(Object)this;if(!(menu.getPlayer() instanceof ServerPlayer player)||player.containerMenu!=menu||plan==null||!menu.isValidMenu()){ae2craftingtime$variants.close();return;}if(plan!=ae2craftingtime$sentPlan){ae2craftingtime$sentPlan=plan;var revision=ae2craftingtime$revisions.advance();if(revision<=0){ae2craftingtime$variants.close();return;}var entries=plan.getEntries();for(var offset=0;offset<entries.size();offset+=256){var count=Math.min(256,entries.size()-offset);var bits=new BitSet(count);for(var row=0;row<count;row++)if(((RecurrentPlanEntry)entries.get(offset+row)).ae2craftingtime$recurrent())bits.set(row);if(!bits.isEmpty())StatsNetwork.sendTo(player,PlanRecurrenceS2C.of(menu.containerId,revision,entries.size(),offset,count,bits));}}if(ae2craftingtime$revisions.value()<=0){ae2craftingtime$variants.close();return;}ae2craftingtime$variants.broadcast(plan,getGrid(),player,menu.containerId,ae2craftingtime$revisions.value(),true);}
 @Inject(method="removed",at=@At("RETURN")) private void close(net.minecraft.world.entity.player.Player player,CallbackInfo ci){ae2craftingtime$variants.close();}
 @Override public long ae2craftingtime$summaryRevision(){return ae2craftingtime$revisions.value();}
 @Override public boolean ae2craftingtime$apply(PlanRecurrenceChunk chunk){if(plan==null||!chunk.validFor(((CraftConfirmMenu)(Object)this).containerId,ae2craftingtime$revisions.value(),plan.getEntries().size()))return false;var bits=chunk.rows();for(var row=bits.nextSetBit(0);row>=0;row=bits.nextSetBit(row+1)){var e=plan.getEntries().get(chunk.offset()+row);if(e.getMissingAmount()>0)((RecurrentPlanEntry)e).ae2craftingtime$recurrent(true);}return true;}
 @Override public boolean ae2craftingtime$applyStoredVariants(PlanRecurrenceChunk chunk,long updateRevision){if(plan==null)return false;return ae2craftingtime$variantClient.apply(chunk,updateRevision,((CraftConfirmMenu)(Object)this).containerId,ae2craftingtime$revisions.value(),plan.getEntries().size(),(row,set)->{var e=plan.getEntries().get(row);((RecurrentPlanEntry)e).ae2craftingtime$storedVariant(com.ctux.ae2craftingtime.core.PlanStoredVariantLifecycle.show(e.getWhat() instanceof appeng.api.stacks.AEItemKey,e.getMissingAmount(),set,true));});}
}
