package com.ctux.ae2craftingtime.testdriver;

public enum ScenarioState {
    STARTING,
    WORLD_READY,
    TERMINAL_OPEN,
    PLAN_OPEN,
    PLAN_STABLE,
    ADDON_CPU_SELECTED,
    ADDON_CRAFT_SUBMITTED,
    ADDON_SAMPLE_RECORDED,
    ADDON_PLAN_OPEN,
    BASE_CHECKED,
    SORTS_CHECKED,
    TOOLTIP_CHECKED,
    RESULT_WRITTEN,
    QUIT_REQUESTED,
    FAILED
}
